/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package marvelsgroup;
import java.sql.*;
import java.util.Date;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author hp-pc
 */
public class forgotPassword extends javax.swing.JFrame {

    /**
     * Creates new form forgotPassword
     */
    Connection conn=null;
    public forgotPassword() {
        initComponents();
        conn=MySQLConnect.ConnectDB();
        sendmailbutton.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usernameinputbox = new javax.swing.JTextField();
        sendmailbutton = new javax.swing.JButton();
        cancelbutton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Trouble Logging In?");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("User Name");

        usernameinputbox.setNextFocusableComponent(sendmailbutton);
        usernameinputbox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameinputboxFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameinputboxFocusLost(evt);
            }
        });

        sendmailbutton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        sendmailbutton.setText("Send Recovery Mail");
        sendmailbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendmailbuttonActionPerformed(evt);
            }
        });

        cancelbutton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cancelbutton.setText("Cancel");
        cancelbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelbuttonActionPerformed(evt);
            }
        });

        jLabel4.setForeground(java.awt.Color.red);
        jLabel4.setText("   ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sendmailbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(cancelbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(usernameinputbox))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(usernameinputbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sendmailbutton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancelbutton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void sendmailbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendmailbuttonActionPerformed
        String senderdata[]=new String[3];
        senderdata=getSenderData();
        final String fsenderdata[]={senderdata[0],senderdata[1],senderdata[2]}; 
        final String ctime=(new SimpleDateFormat("MM/dd/yyyy HH:mm:ss").format(new Date()))+" ";
        Thread t;
        t=new Thread(new Runnable() {
            @Override
            public void run() {
                PasswordRecoveryMailService.sendRecoveryMail(fsenderdata[0], fsenderdata[1], fsenderdata[2], ctime);
            }
        });
        t.start();
        JOptionPane.showMessageDialog(null, "You will recieve the mail shortly. Incase you don't recieve it, try again later!");
        this.dispose();
    }//GEN-LAST:event_sendmailbuttonActionPerformed

    private void usernameinputboxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameinputboxFocusGained
        jLabel4.setText("   ");
        usernameinputbox.setText("");
        sendmailbutton.setEnabled(false);
    }//GEN-LAST:event_usernameinputboxFocusGained

    private void usernameinputboxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameinputboxFocusLost
        int flag=checker();
        if(flag==1)
        {
            sendmailbutton.setEnabled(true);
        }
        else if(flag==0)
        {
            jLabel4.setText("Invalid Username!");
            sendmailbutton.setEnabled(false);
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Internal Error!");
        }
    }//GEN-LAST:event_usernameinputboxFocusLost

    private void cancelbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelbuttonActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_cancelbuttonActionPerformed

    public int checker()
    {
        int flag=0;
        PreparedStatement pst=null;
        ResultSet rs=null;
        try
        {
            String st="select * from logindetails where username=?";
            pst=conn.prepareStatement(st);
            pst.setString(1, usernameinputbox.getText());
            rs=pst.executeQuery();
            if(rs.first())
                return 1;
            if(!rs.first())
                return 0;
        }
        catch(SQLException e)
        {
            e.printStackTrace();
        }
        return -1;
    }
    
    public String[] getSenderData()
    {
        String data[]=new String[3];
        PreparedStatement pst=null;
        ResultSet rs=null;
        try
        {
            String st="select * from logindetails where username=?";
            pst=conn.prepareStatement(st);
            pst.setString(1, usernameinputbox.getText());
            rs=pst.executeQuery();
            rs.first();
            data[0]=rs.getString("emailid");
            data[1]=rs.getString("username");
            data[2]=rs.getString("password");
            return data;
        }
        catch(SQLException e)
        {
            e.printStackTrace();
        }
        return data;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(forgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(forgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(forgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(forgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new forgotPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton sendmailbutton;
    private javax.swing.JTextField usernameinputbox;
    // End of variables declaration//GEN-END:variables
}
